app = "cyber-x"
primary_region = "ams"

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = false
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
