// lib/jokes.js — CYBER X Jokes Library
'use strict'

const JOKES = [
  // ── GENERAL ──────────────────────────────────────────────────────
  "Why don't scientists trust atoms? Because they make up everything!",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why don't eggs tell jokes? They'd crack each other up!",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Did you hear about the mathematician who's afraid of negative numbers? He'll stop at nothing to avoid them!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "I used to hate facial hair but then it grew on me.",
  "Why don't skeletons fight each other? They don't have the guts!",
  "What do you call a fish without eyes? A fsh!",
  "Why can't you give Elsa a balloon? Because she'll let it go!",
  "I asked the librarian if they had books about paranoia. She whispered 'They're right behind you!'",
  "What do you call cheese that isn't yours? Nacho cheese!",
  "Why did the bicycle fall over? Because it was two-tired!",
  "I told my doctor that I broke my arm in two places. He told me to stop going to those places!",
  "What do you call a sleeping dinosaur? A dino-snore!",
  "Why did the math book look so sad? Because it had too many problems!",
  "What do you call a fake noodle? An impasta!",
  "Why did the golfer bring an extra pair of pants? In case he got a hole in one!",
  "What do you call a bear with no teeth? A gummy bear!",
  "I would tell you a construction joke but I'm still working on it!",
  "Why don't scientists trust atoms? Because they make up everything!",
  "What did the ocean say to the beach? Nothing, it just waved!",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "What do you call a lazy kangaroo? A pouch potato!",
  "Why did the coffee file a police report? It got mugged!",
  "What do you call a snowman with a six-pack? An abdominal snowman!",
  "Why did the stadium get hot after the game? All the fans left!",
  "What do you call a dinosaur that crashes their car? Tyrannosaurus wrecks!",
  "Why did the invisible man turn down the job offer? He couldn't see himself doing it!",
  "What do you call a pig that does karate? A pork chop!",

  // ── NAIJA / NIGERIA JOKES ─────────────────────────────────────────
  "Nigerian father: Why did you get 98 out of 100? Me: Because I tried my best. Father: Who asked you to try your best? Get 100!",
  "NEPA took light in the middle of my dream. I woke up angry because the generator in my dream refused to start!",
  "In Nigeria we don't say I love you. We say 'Have you eaten?' and I think that's beautiful.",
  "Nigerian mom: Go and greet your uncle. Me: Good afternoon sir. Uncle: You're looking well fed. Me: Thank you sir. Mom: Don't be rude!",
  "The way Nigerian parents say 'we will see' means you are finished.",
  "Nigerian parents don't ask you to lower the TV volume. They just turn it off completely.",
  "In Nigeria, when your mom calls your full name, you have approximately 3 seconds to reflect on every bad thing you've ever done.",
  "Nigerian uncle at Christmas: So what are you doing with your life? Me: I'm studying. Uncle: Study and chop? You better find work!",
  "NEPA gives light at 3am just to remind you they exist.",
  "Nigerian parents will tell you to go and sleep, then come back 5 minutes later to ask why you are sleeping.",
  "The most dangerous sentence in Nigeria: 'Come, I want to show you something.'",
  "Nigerian mom: I didn't beat you enough as a child. Me: You beat me every day. Mom: Exactly.",
  "In Nigeria, the remote control is always lost but somehow parents find it immediately when they need it.",
  "Nigerian traffic: 30 minutes to go 2km. This is not a traffic jam, this is a lifestyle.",
  "When a Nigerian parent says 'It's a small thing', prepare for the hardest task of your life.",

  // ── TECH / PROGRAMMER JOKES ───────────────────────────────────────
  "Why do programmers prefer dark mode? Because light attracts bugs!",
  "A SQL query walks into a bar, walks up to two tables and asks 'Can I join you?'",
  "Why do Java developers wear glasses? Because they don't C#!",
  "There are 10 types of people in the world: those who understand binary and those who don't.",
  "Why was the JavaScript developer sad? Because he didn't know how to 'null' his feelings!",
  "A programmer's wife tells him: 'Go to the store and get a gallon of milk, and if they have eggs, get a dozen.' He came home with 12 gallons of milk.",
  "Why did the developer go broke? Because he used up all his cache!",
  "How many programmers does it take to change a light bulb? None, that's a hardware problem!",
  "Why do programmers always mix up Halloween and Christmas? Because Oct 31 == Dec 25!",
  "I told my computer I needed a break. Now it won't stop sending me Kit Kat ads.",
  "Why was the computer cold? It left its Windows open!",
  "A programmer had a problem. He thought 'I'll solve it with threads.' Now he two has problems.",
  "Why do programmers hate nature? It has too many bugs and no documentation!",
  "What's a computer's favorite snack? Microchips!",
  "Why did the programmer quit his job? Because he didn't get arrays!",
  "Debugging is like being the detective in a crime movie where you are also the murderer.",
  "Why was the function sad after a breakup? It couldn't find its return value!",
  "A good programmer looks both ways before crossing a one-way street.",
  "What do you call 8 hobbits? A hobbyte!",
  "Why don't programmers like to go outside? The sun causes too many glares on their screens!",

  // ── SCHOOL / STUDENTS ─────────────────────────────────────────────
  "Teacher: Why are you late? Student: Because of the sign outside. Teacher: What sign? Student: The one that says 'School ahead, go slow'!",
  "Student: Teacher I don't have a pen. Teacher: And whose fault is that? Student: The pen manufacturer!",
  "Teacher: If I gave you 2 cats and another 2 cats, how many would you have? Student: 5. Teacher: No, 4. Student: I already have one at home!",
  "My math teacher called me average. How mean!",
  "Teacher: You copied from your friend didn't you? Student: How did you know? Teacher: Because when your friend wrote 'I don't know' you wrote 'Me neither'!",
  "Student to parent: I failed my exam because the boy next to me is very tall. Parent: What? Student: He covered the board!",
  "Teacher: What comes after a sentence? Student: An appeal!",
  "Why did the student eat his homework? Because the teacher told him it was a piece of cake!",
  "Teacher: Name a liquid that can't freeze. Student: Hot water!",
  "School is a place where your parents send you to solve their problems.",

  // ── RELATIONSHIP JOKES ────────────────────────────────────────────
  "My girlfriend told me she wanted to feel special on her birthday. I bought her a calculator.",
  "I asked my dog what two minus two is. He said nothing.",
  "Why did the man put his money in the blender? Because he wanted to make some liquid assets!",
  "My wife told me I had to stop acting like a flamingo. I had to put my foot down.",
  "I asked my wife what she wanted for Christmas. She said 'Nothing would make her happier than a diamond necklace.' So I got her nothing.",
  "My wife and I were happy for 20 years. Then we met!",
  "I told my wife she should embrace her mistakes. She gave me a hug.",
  "Behind every angry woman is a man who has absolutely no idea what he did wrong.",
  "My girlfriend said she wanted to feel like a princess. So I made her shake hands with a lot of strangers and wave from a distance.",
  "I love you with all my butt. I would say heart but my butt is bigger.",

  // ── FOOD JOKES ────────────────────────────────────────────────────
  "Why did the banana go to the doctor? Because it wasn't peeling well!",
  "What do you call a stolen yam? A hot potato!",
  "I'm on a seafood diet. I see food and I eat it.",
  "Why did the cookie go to the doctor? Because it felt crummy!",
  "What do you call a sad strawberry? A blueberry!",
  "Why did the chef get arrested? He was caught beating an egg!",
  "What do elves make sandwiches with? Shortbread!",
  "Why did the orange stop? Because it ran out of juice!",
  "What did the plate say to the other plate? Dinner's on me!",
  "I tried to make a belt out of watches. It was a waist of time!",
  "Jollof rice argument: Nigerian jollof vs Ghanaian jollof. The answer is always Nigerian. End of discussion.",
  "Me: I'll just have a little snack. The snack: *entire pot of egusi soup*",
  "Nigerian party food hits different at midnight. Same food, different energy.",

  // ── ANIMAL JOKES ──────────────────────────────────────────────────
  "What do you call a sleeping bull? A bulldozer!",
  "Why don't elephants use computers? Because they're afraid of the mouse!",
  "What do you call a dog magician? A labracadabrador!",
  "Why did the cat sit on the computer? To keep an eye on the mouse!",
  "What do you call a fish wearing a crown? King of the sea!",
  "Why did the lion eat the tightrope walker? Because it wanted a well-balanced meal!",
  "What do you call a cow that plays guitar? A moo-sician!",
  "Why don't oysters share? Because they're shellfish!",
  "What do you call a monkey that loves chips? A chipmunk!",
  "Why did the chicken cross the road? To get to the other side... of the jollof rice!",

  // ── WORK / OFFICE JOKES ───────────────────────────────────────────
  "Boss: You're late! Employee: I'm not late, everyone else is early!",
  "My boss told me to have a good day. So I went home!",
  "I asked my boss if I could leave work early. He said yes if I made up the time. I said sure, it's 35:00!",
  "Why did the employee get fired from the calendar factory? He took a day off!",
  "I told my boss three companies were after me and I needed a raise. He asked which companies. I said the gas, electric, and water companies!",
  "The best part about working from home is the commute. It's amazing.",
  "My CV says I work well under pressure. I wrote that under pressure.",
  "Office rule: The person who arrives last makes the tea. I've been arriving at 4am for 3 years.",
  "My job is secure. Nobody else wants it.",
  "I finally got a job at the library but it only lasted a day. It was overdue!",

  // ── DARK HUMOR ────────────────────────────────────────────────────
  "I have a joke about infinity but I don't know where to start.",
  "I told a joke about paper. It was tearable.",
  "My friend keeps saying 'cheer up man it could be worse, you could be stuck underground in a hole full of water.' I know he means well.",
  "I asked God for a bike but I know God doesn't work that way. So I stole a bike and asked for forgiveness.",
  "A pessimist's blood type is always B-negative.",
  "The cemetery is so crowded. People are just dying to get in.",
  "My wife told me I had to stop acting childish. I told her to get out of my pillow fort.",
  "I have a lot of growing up to do. I realized that the other day inside my fort.",
  "Some people age like fine wine. Others age like milk.",

  // ── PUNS ─────────────────────────────────────────────────────────
  "I'm reading a horror story in Braille. Something bad is about to happen, I can feel it.",
  "Time flies like an arrow. Fruit flies like a banana.",
  "I used to be a banker but I lost interest.",
  "Becoming a vegetarian is a huge missed steak.",
  "I'm trying to organize a hide and seek competition but good players are really hard to find.",
  "I used to hate clocks but now I've come around.",
  "I was wondering why the ball kept getting bigger and bigger. Then it hit me.",
  "I'm friends with all electricians. We have good current connections.",
  "Did you hear about the guy who invented Lifesavers? He made a mint!",
  "I used to work in a shoe recycling shop. It was sole destroying.",
  "What's the best thing about Switzerland? I don't know but the flag is a big plus.",
  "I tried to write a joke about clocks but I ran out of time.",
  "Why can't a nose be 12 inches long? Because then it would be a foot!",
  "I have a joke about construction but I'm still building up to it.",
  "Did you hear about the guy who invented the knock knock joke? He won the no-bell prize!",

  // ── RANDOM FUNNY ──────────────────────────────────────────────────
  "The first five days after the weekend are always the hardest.",
  "My bed is a magical place where I suddenly remember everything I forgot to do.",
  "I clean my house every day. Just kidding, I just move the mess from one room to another.",
  "I told myself I should stop drinking. But I'm not about to listen to a drunk who talks to himself.",
  "I don't need a hair stylist. My pillow gives me a new hairstyle every morning.",
  "I always say morning instead of good morning because if it was good I'd be asleep.",
  "My wallet is like an onion. When I open it, it makes me cry.",
  "I was going to tell a time traveling joke but you didn't like it.",
  "Common sense is like deodorant. The people who need it most never use it.",
  "Nothing is lost until your mom can't find it.",
  "I'm not lazy. I'm on energy saving mode.",
  "My life is a constant battle between wanting to eat everything and wanting to look good.",
  "I don't have a bad handwriting. I have my own font.",
  "When nothing goes right, go left.",
  "I put my phone in airplane mode and threw it up in the air. Worst transformer ever.",
  "I would lose weight but I hate losing.",
  "My superpower is holding all my problems inside until I explode.",
  "I need a 6 month vacation twice a year.",
  "Brain: Let's go to sleep. Me: No, let's think about every mistake we've ever made.",
  "Some days I amaze myself. Other days I look for my phone while holding it.",
  "I'm not arguing, I'm just explaining why I'm right.",
  "At what age is it appropriate to tell my dog that he's adopted?",
  "My GPS said 'Turn right' and I said 'I barely know left'.",
  "I asked Siri why I'm still single. She opened the front camera.",
  "People say I act like I don't care. It's not an act.",
  "Exercise? I thought you said extra fries!",
  "I'm not short. I'm fun sized.",
  "My room is not messy. It's an obstacle course designed to keep me fit.",
  "I hate when I think I'm buying organic vegetables and when I get home I discover they're regular donuts.",
  "I follow the diet rules: If nobody saw you eat it, it has zero calories.",
]

function getRandom() {
  return JOKES[Math.floor(Math.random() * JOKES.length)]
}

function getByCategory(category) {
  const cats = {
    naija:  JOKES.filter((_, i) => i >= 30 && i <= 44),
    tech:   JOKES.filter((_, i) => i >= 45 && i <= 64),
    school: JOKES.filter((_, i) => i >= 65 && i <= 74),
    food:   JOKES.filter((_, i) => i >= 85 && i <= 97),
    work:   JOKES.filter((_, i) => i >= 108 && i <= 117),
    puns:   JOKES.filter((_, i) => i >= 128 && i <= 142),
  }
  const list = cats[category?.toLowerCase()]
  if (!list?.length) return getRandom()
  return list[Math.floor(Math.random() * list.length)]
}

module.exports = { getRandom, getByCategory, JOKES }
